name: Build and lint on Pull Request

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches:
      - 'main'
    paths: ['src/**', index.html, .github/workflows/*.yml]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.6.1'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build Webpage & Documentation
        run: npm run build
  lint:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=21.6.1'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build Webpage & Documentation
        run: npm run lint
